apiVersion: batch/v1
kind: Job
metadata:
  name: cvesearch
spec:
  template:
    metadata:
      labels:
        app: "cvesearch"
    spec:
      containers:
        - name: "cvesearch"
          image: "akoderman/cvesearch:latest"
          resources:
            requests:
              memory: "20Mi"
            limits:
              memory: "300Mi"
          env:
          - name: PYTHONDONTWRITEBYTECODE
            value: "1"
          workingDir: /cve-search/sbin
          command: ["python"]
          args: ["db_updater.py", "-v"]
          volumeMounts:
            - name: "cvesearch-conf"
              mountPath: "/cve-search/etc"
      restartPolicy: Never
      volumes:
        - name: "cvesearch-conf"
          configMap:
            name: "cvesearch-configmap"


